[package]
name = "fvideo"
version = "0.1.0"
authors = ["Luke Hsiao <lwhsiao@stanford.edu>"]
edition = "2018"
description = "A collection of binaries for foveated video encoding."
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "recording"

[[bin]]
name = "fvideo"

[dependencies]
anyhow = "1.0.32"
eyelink-rs = {path = "../eyelink-rs"}
ffmpeg-next = "4.3.6"
lazy_static = "1.4.0"
log = "0.4.11"
num-rational = "0.3.0"
pretty_env_logger = "0.4.0"
regex = "1.3.9"
sdl = "0.3.6"
sdl2 = "0.34.3"
structopt = "0.3.18"
thiserror = "1.0.20"
x264 = {path = "../x264-rs"}

[profile.release]
debug = true
