[package]
name = "fvideo"
version = "0.1.0"
authors = ["Luke Hsiao <lwhsiao@stanford.edu>"]
edition = "2018"
description = "Calibrate and record eye data while playing a video with mpv."
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
eyelink-rs = {path = "../eyelink-rs"}
ffmpeg-next = "4.3.4"
log = "0.4.11"
num-rational = "0.3.0"
pretty_env_logger = "0.4.0"
sdl = "0.3.6"
sdl2 = "0.34.2"
structopt = "0.3.16"
thiserror = "1.0.20"

[profile.release]
debug = true
