on: [push, pull_request]

name: rust

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install libx264-dev ffmpeg libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev llvm-dev libudev-dev
      - name: Enable universe
        run: sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install ca-certificates
      - name: Install eyelink signing key
        run: sudo apt-key adv --fetch-keys https://apt.sr-research.com/SRResearch_key
      - name: Add SRResearch apt repository
        run: sudo add-apt-repository 'deb [arch=amd64] https://apt.sr-research.com SRResearch main' && sudo apt-get update
      - name: Install eyelink SDK
        run: sudo apt-get install eyelink-display-software
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install libx264-dev ffmpeg libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev llvm-dev libudev-dev
      - name: Enable universe
        run: sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install ca-certificates
      - name: Install eyelink signing key
        run: sudo apt-key adv --fetch-keys https://apt.sr-research.com/SRResearch_key
      - name: Add SRResearch apt repository
        run: sudo add-apt-repository 'deb [arch=amd64] https://apt.sr-research.com SRResearch main' && sudo apt-get update
      - name: Install eyelink SDK
        run: sudo apt-get install eyelink-display-software
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Linting
        run: cargo clippy --all-targets --all-features -- -D warnings
