on: [push, pull_request]

name: rust

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - id: deps
        run: sudo apt-get update && sudo apt-get install libx264-dev ffmpeg libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev llvm-dev libudev-dev
      - id: eyelink1
        run: wget -O - "http://download.sr-support.com/software/dists/SRResearch/SRResearch_key" | sudo apt-key add -
      - id: eyelink2
        run: sudo add-apt-repository "deb http://download.sr-support.com/software SRResearch main" && sudo apt-get update
      - id: eyelink3
        run: sudo apt-get update && sudo apt-get install eyelink-display-software
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - id: deps
        run: sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4 && sudo apt-get update && sudo apt-get install libx264-dev ffmpeg libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev llvm-dev libudev-dev
      - id: eyelink1
        run: wget -O - "http://download.sr-support.com/software/dists/SRResearch/SRResearch_key" | sudo apt-key add -
      - id: eyelink2
        run: sudo add-apt-repository "deb http://download.sr-support.com/software SRResearch main" && sudo apt-get update
      - id: eyelink3
        run: sudo apt-get update && sudo apt-get install eyelink-display-software
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - id: deps
        run: sudo apt-get update && sudo apt-get install libx264-dev ffmpeg libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev llvm-dev libudev-dev
      - id: eyelink1
        run: wget -O - "http://download.sr-support.com/software/dists/SRResearch/SRResearch_key" | sudo apt-key add -
      - id: eyelink2
        run: sudo add-apt-repository "deb http://download.sr-support.com/software SRResearch main" && sudo apt-get update
      - id: eyelink3
        run: sudo apt-get update && sudo apt-get install eyelink-display-software
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
