on: [push, pull_request]

name: rust

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - id: deps
        run: sudo apt-get update && sudo apt-get install libx264-dev ffmpeg libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev llvm-dev libudev-dev
      - id: eyelink1
        run: wget -O - "http://download.sr-support.com/software/dists/SRResearch/SRResearch_key" | sudo apt-key add -
      - id: eyelink2
        run: sudo add-apt-repository "deb http://download.sr-support.com/software SRResearch main" && sudo apt-get update
      - id: eyelink3
        run: sudo apt-get update && sudo apt-get install eyelink-display-software
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - id: deps
        run: sudo apt-get update && sudo apt-get install libx264-dev ffmpeg libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev llvm-dev libudev-dev
      - id: eyelink1
        run: wget -O - "http://download.sr-support.com/software/dists/SRResearch/SRResearch_key" | sudo apt-key add -
      - id: eyelink2
        run: sudo add-apt-repository "deb http://download.sr-support.com/software SRResearch main" && sudo apt-get update
      - id: eyelink3
        run: sudo apt-get update && sudo apt-get install eyelink-display-software
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Linting
        run: cargo clippy --all-targets --all-features -- -D warnings
